development:
  adapter: postgresql
  encoding: unicode
  database: nss_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: nss_test
  pool: 5
  timeout: 5000

production:
  adapter:  postgresql
  encoding: unicode
  pool: 5
  database: d48ag9j0k37o8s
  username: yuuieujqpcgdej
  password: JhL4VaOKQpoYsQDrsDjzLIVXXO
  host: ec2-54-243-230-139.compute-1.amazonaws.com
  port: 5432
